### ISSUE TITLE
Multicore processing of lightweight variables

### ISSUE THREAD

**Issue by Peder2911** [prio-data/priogrid#12]
Currently, many variables with insignificant memory footprint and runtimes of around 1 minute are being done in sequence on a single thread. This is really inefficient, and easily done in parallel. The only issue with this is that if we are opting for parallel processing within gen functions as well, we need to be mindful of not running several things at once in parallel.

Perhaps we should discuss this at the office at some point, I am just posting this to start the discussion here.

**Comment by Peder2911** [comment]
Probably not a good idea. Would make it too complicated to keep track of what needs to be parallel and what needs to be serial. Also, gains are insignificant compared to the effort required.

**Comment by kvelleby** [comment]
Current implementation uses parallel::mclapply() in combination with options("mc.cores"). The benefit of this is that parallel::mclapply() is just lapply() when mc.cores = 1, or you are on Windows.

While not (always parallel), we also use data.table in some places where we need the extra speed. Using packages that automatically parallelize certain operations (such as data.table) I think is a good option.
