### ISSUE TITLE
epr demoted/promoted

### ISSUE THREAD

**Issue by kvelleby** [prio-data/priogrid#21]
whether or not the political status of any regionally based group within a cell got improved (in case of epr_promoted) or reduced (in case of epr_demoted).

**Comment by vildebl** [comment]
gen_demoted() and gen_promoted() generates count variables of the number of groups that have reduced or improved their political status. Should it be limited to regionally-based groups? Count variable ok?

**Comment by kvelleby** [comment]
From the GeoEPR codebook (https://icr.ethz.ch/data/epr/geoepr/EPR_2019_Codebook_GeoEPR.pdf):

Only when groups have a distinct regionally based settlement pattern, that is, when they
are either coded as regionally based (1), regional and urban (3) or aggregate (6), we assign
a polygon that represents their settlement area.  Statewide groups receive their country’s polygon from the CShapes 2.0 dataset.

I am tempted to suggest that we only include the regionally based, the urban, and the aggregate groups (that have a special settlement area). If people want to include the statewide groups, that is easily accessible from the EPR dataset.

**Comment by vildebl** [comment]
This is now fixed. All epr variables now only include regionally based, regional & urban and aggregate groups; those that have substate polygons assigned.
