### ISSUE TITLE
Functionality for interpolating pgdf data to arbitrary temporal resolutions

### ISSUE THREAD

**Issue by kvelleby** [prio-data/priogrid#22]
Commonly, results from gen_*() functions return data for some specific time interval, e.g. five-year, yearly, monthly, etc. I suggest we should have a interpolate_pg_timeseries() function that takes a pgdf (x, y, date_var, variable) and returns a new interpolated dataset at any chosen temporal resolution. One solution to this is to build a raster::stack() with all cross-sections, both those with data and those with missing data, and then raster::approxNA() the missing data. The function should return a new pgdf (e.g. using priogrid::raster_to_tibble())

**Comment by vildebl** [comment]
interpolate_pg_timeseries() is now included in utility_functions.  Fully compatible with all temporal resolutions specified by seq.Date(), but recommended to use month, quarter, or year.
