### ISSUE TITLE
vector_to_pg using raster::rasterize() and sf objects

### ISSUE THREAD

**Issue by kvelleby** [prio-data/priogrid#28]
See [12de835](https://github.com/prio-data/priogrid/commit/12de8359b3d85723edebc4d3a91c6e79ca059a33).

I have used raster::rasterize() with sf objects before, but with the latest update (3.3-7), it seems not to work? One solution, I think, is to transform to sp before rasterizing: `as(sfdf, "Spatial")`. Another would be to look for other solutions. fasterize might be one? https://r-spatial.github.io/stars/ is probably the long term solution, but unsure about how well it works today.

**Comment by vildebl** [comment]
It looks like raster::rasterize() is working on sf objects again (package version 3.3-13). It's at least working on sf point data. I updated vector_to_pg() with rasterize because fasterize does not take point data, only polygons.
